### ISSUE TITLE
dark-mode left my system in a mixed state

### ISSUE THREAD

**Issue by chdiza** [sindresorhus/dark-mode#3]
After playing around with dark-mode, it left my system in a mixed-mode state.  The menubar is dark, but the backgrounds for the Dock and the Cmd-Tab display are light.

This mixed-state persists no matter what I do in System Preferences.  It also persists after full reboots.

**Comment by chdiza** [comment]
dark-mode was only intermittently successful before I noticed the mixed state.

I found that using it as a "toggle" was far buggier than using it as a setter (`dark-mode --mode Dark`).

**Comment by sindresorhus** [comment]
Known issue: https://github.com/sindresorhus/node-dark-mode/issues/1

No workaround as far as I know.

**Comment by chdiza** [comment]
I may have discovered something that can serve as a hint for how to fix this.  I did `defaults delete` for all my user-domain preferences and logged out.  So far, the problem has not appeared.  This suggests that dark-mode is leaving something bogus around in ~/library/preferences.

I'll let you know if it returns.

**Comment by bezhermoso** [comment]
@chdiza Hi!

I am having the same problems and I was wondering what user domain preferences did you have to reset in order to resolve this?

Thanks!

**Comment by chdiza** [comment]
I blasted *ALL* of them.  I don't have anything more specific than that, sorry.  I never used this app again after that bad experience.

**Comment by bezhermoso** [comment]
@chdiza Ah! :) That's what I ended up doing as well. Thanks!

**Comment by nicokratky** [comment]
@chdiza @bezhermoso  But, how did you "blast" all of the user-domain preferences?

**Comment by bezhermoso** [comment]
@nicokratky Personally I just cleared out `~/Library/{Caches,Preferences,Containers,Global Containers}` -- deleted just the _contents_ but not the folders. That pretty much cleared out existing preferences + most app data though, so consider that: https://discussions.apple.com/thread/7058719?start=0&tstart=0

**Comment by nicokratky** [comment]
@bezhermoso Thanks! Worked for me! :+1:

**Comment by skullk1d** [comment]
I solved the problem, but what did it for me was restoring ~/Library/Preferences to a previous time machine backup.

**Comment by JayBrown** [comment]
First off: thanks for messing up my system.

Secondly: here's how I did it… (1) delete all visible contents of the user's Preferences folder and copied all Preferences contents from a two-days-old clone back onto the boot volume; (2) replaced Containers & Group Containers (the folders, not the contents) with older versions of those directories from the clone; (3) reset all system & user caches with TinkerTool System & reboot.

Lastly: You should really add a big warning message to your readme.md and have dark-mode removed from homebrew. Anyhow, it was worth a try, I guess.

**Comment by chauncey-garrett** [comment]
I too experienced the issue where my system was left in a mixed state. Toggling "Use dark menu bar and Dock" under System Preferences > General would only change the menu bar; the Dock would remain the lighter color.

![2016-11-06 at 12 16](https://cloud.githubusercontent.com/assets/302358/20040346/f9c2ebf6-a41a-11e6-88ae-addb11a320c9.png)

Short of the nuclear option to delete everything in `~/Library/Preferences`, I previously tried deleting the Dock's preference files and several other options without success.  In particular, setting the defaults with this command didn't do what I hoped (not even sure it's currently valid under Sierra):

`defaults write NSGlobalDomain AppleInterfaceStyle Dark; killall Dock`

What did finally resolve this issue was using [Panda](https://github.com/pablosproject/Panda-Mac-app)'s "Reset Dark Mode Settings" option.

![image](https://cloud.githubusercontent.com/assets/302358/20040296/17274d5a-a41a-11e6-9fca-cb40e6a15470.png)

Whatever Panda is doing under the hood here may be useful in solving this longstanding issue.

**Comment by jamesstout** [comment]
@bezhermoso the file that `dark-mode` writes to is `~/Library/Preferences/ByHost/.GlobalPreferences.[Hardware UUID].plist` So you just need to delete that file.

This is due to the prefs been read and written for this specific machine, see `kCFPreferencesCurrentHost` in [dark-mode.m](https://github.com/sindresorhus/dark-mode/blob/7e4fb212e92d2ae59c6760147f11263524aa3a58/dark-mode.m#L6):

```objc 
CFPreferencesCopyValue((CFStringRef)@"AppleInterfaceStyle", kCFPreferencesAnyApplication, kCFPreferencesCurrentUser, kCFPreferencesCurrentHost));
 ```

also [L30 for the write](https://github.com/sindresorhus/dark-mode/blob/7e4fb212e92d2ae59c6760147f11263524aa3a58/dark-mode.m#L30).

It also means that all apps use these prefs, as `kCFPreferencesAnyApplication ` is used.

I wonder if Finder and the Dock use that same pref? 

If you use the system preferences general pane, and toggle the dark mode on, then this is written to `~/Library/Preferences/.GlobalPreferences.plist`

```xml
<key>AppleInterfaceStyle</key>
<string>Dark</string>
```
If you toggle it off, the entire key is missing.

So you could start with system preferences general to light mode (no key in `~/Library/Preferences/.GlobalPreferences.plist`), run `dark-mode` to toggle, which writes 

```xml
<key>AppleInterfaceStyle</key>
<string>Light</string>
```

to `~/Library/Preferences/ByHost/.GlobalPreferences.[Hardware UUID].plist`

Then toggle again with `dark-mode`, giving:

```xml
<key>AppleInterfaceStyle</key>
<string>Dark</string>
```

Then activate dark mode via system preferences general. This writes the `Dark` key to `~/Library/Preferences/.GlobalPreferences.plist`

Double check:

```shell
james@Jamess-iMac: ~/Library/Preferences/ByHost
$ plutil -p ../.GlobalPreferences.plist | grep AppleInterfaceStyle
  "AppleInterfaceStyle" => "Dark"

james@Jamess-iMac: ~/Library/Preferences/ByHost
$ defaults read -g AppleInterfaceStyle
Dark
```

Then deactivate dark mode via system preferences general which removes the key from `~/Library/Preferences/.GlobalPreferences.plist` completely.

Double check:

```shell
$ plutil -p ../.GlobalPreferences.plist | grep AppleInterfaceStyle

james@Jamess-iMac: ~/Library/Preferences/ByHost
$ defaults read -g AppleInterfaceStyle
2016-11-26 22:06:13.763 defaults[15173:921431]
The domain/default pair of (kCFPreferencesAnyApplication, AppleInterfaceStyle) does not exist
```
At this point the dock and menu bar are still dark (and look good), as is the `dark-mode` mode:

```shell
$ dark-mode --mode
Dark

$ plutil -p .GlobalPreferences.B2082C02-FB01-53DB-BA79-5A4063562639.plist | grep AppleInterfaceStyle
  "AppleInterfaceStyle" => "Dark"
```

Now, toggle to `dark-mode` light:

```shell
james@Jamess-iMac: ~/Library/Preferences/ByHost
$ dark-mode

james@Jamess-iMac: ~/Library/Preferences/ByHost
$ dark-mode --mode
Light

james@Jamess-iMac: ~/Library/Preferences/ByHost
$ plutil -p .GlobalPreferences.B2082C02-FB01-53DB-BA79-5A4063562639.plist | grep AppleInterfaceStyle
  "AppleInterfaceStyle" => "Light"
```
Looks good except:

```shell
$ defaults read  -g AppleInterfaceStyle
2016-11-26 22:12:20.561 defaults[15338:956156]
The domain/default pair of (kCFPreferencesAnyApplication, AppleInterfaceStyle) does not exist
```

But then...

```shell
$ defaults -currentHost read -g AppleInterfaceStyle
Light
```

I don't know how the defaults/prefs system works that much, so I've started to read [the Apple docs](https://developer.apple.com/library/content/documentation/CoreFoundation/Conceptual/CFPreferences/Concepts/PreferenceDomains.html#//apple_ref/doc/uid/20001168-CJBEJBHH)

> Table 1 shows all of the preference domains. The routines for retrieving preferences search through the preference domains in the order shown here until they find the requested key. Thus, if a preference is not found in a more user-specific and application-specific domain, the routines search the more global domains for the information.

![screen shot 2016-11-26 at 11 00 16 pm](https://cloud.githubusercontent.com/assets/1576190/20641127/6092eee6-b42c-11e6-862f-ad2cb1cfcdb2.png)

So, at the point I got to above, there was no global default for AppleInterfaceStyle, but there was one for the host.

Last thing ... activate dark mode via system preferences general. This writes the `Dark` key to `~/Library/Preferences/.GlobalPreferences.plist`

Double check:

```shell
james@Jamess-iMac: ~/Library/Preferences/ByHost
$ plutil -p ../.GlobalPreferences.plist | grep AppleInterfaceStyle
  "AppleInterfaceStyle" => "Dark"

james@Jamess-iMac: ~/Library/Preferences/ByHost
$ defaults read -g AppleInterfaceStyle
Dark
```

However:

```shell
james@Jamess-iMac: ~/Library/Preferences/ByHost
$ defaults -currentHost read -g AppleInterfaceStyle
Light

james@Jamess-iMac: ~/Library/Preferences/ByHost
$ dark-mode --mode
Light
```

At this point, we have a global pref for dark and a host pref for light

My Dock is still in light mode, and my menu bar has sort of gone dark but looks a mess:

![screen shot 2016-11-26 at 11 16 37 pm](https://cloud.githubusercontent.com/assets/1576190/20641221/789f1fbc-b42e-11e6-85d3-153addbb16f1.png)

Given the search order above, I think apps should find the ByHost pref set to Light - search order 1:

> Current User, Current Application, Current Host

If you then switch back to light via system general, my menubar looks good, dock stays light.

So now I'm into pref caching and restarting apps and `syncdefaultsd` and `cfprefsd` and I'm thinking this has taken more time than I expected.

One more thing, dark-mode doesn't call [CFPreferencesSynchronize](https://developer.apple.com/reference/corefoundation/1515504-cfpreferencessynchronize?language=objc), not sure if important, unless only some parts of the menubar monitor for prefs changes.

I've tried `kCFPreferencesAnyHost` but that leaves the key behind and doesn't fix it. I tried `CFPreferencesSynchronize` before and after the notification. No luck.

To be continued...

**Comment by moshed** [comment]
uch my dark mode is messed up now too. @jamesstout did you have any luck with this? i cant find reference to the keys in the plist no matter whats toggled though so maybe were having slightly different experiences

**Comment by jamesstout** [comment]
@moshed I haven't had chance to look at this any further I'm afraid.

**Comment by justijndepover** [comment]
I've created a pull request that adds a 'reset' argument with the modes. This fixes the problem many have when you set the mode with 'dark-mode' and then change via system preferences.
Note:
It does still does not change the menubar color. I'll look into this when i have more time.

**Comment by justijndepover** [comment]
To use this you have to run the build script and then replace the newly created program with the one in /usr/local/Cellar/dark-mode/1.0.1/bin/

**Comment by moshed** [comment]
to anyone ending up here looking for an easier way `osascript -e "tell application \"System Events\" to tell appearance preferences to set dark mode to not dark mode"` works perfectly for me

**Comment by sindresorhus** [comment]
Sorry about the trouble everyone. I completely missed this issue. I decided to rewrite the tool in Swift and use AppleScript instead. See: https://github.com/sindresorhus/dark-mode/releases/tag/2.0.0
